graph TD
    subgraph rating-store-component[Persistence]
        episode-store[(Episode Store)] --- movie-store 
        title-store[(Title Store)] --- movie-store
        name-store[(Name Store)] --- movie-store
        principal-store[(Principal Store)] --- movie-store
        rating-store[(Rating Store)] --- movie-store
        movie-store([Movie Store])
    end
    server[API Server] --> |query| movie-store
    user((User)) --> |request|server
    imdb-process(IMDb Dataset Processor) --> |Download .tsv.gz  Files|imdb((IMDb Webservice))
    imdb-process --> |populate|movie-store